name: encuestas_app
description: Aplicación de encuestas con almacenamiento local

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.0
  path: ^1.8.3
  path_provider: ^2.1.1
  intl: ^0.18.1
  csv: ^5.0.2
  share_plus: ^7.2.1
  flutter_launcher_icons: ^0.13.1 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/logo.png"
  adaptive_icon_background: "#0143A4"
  adaptive_icon_foreground: "assets/icons/logo.png"